### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by joliss** [shanielh/broccoli-swig#2]
Do you want to add a LICENSE file, and add a "license" key to package.json?

**Comment by shanielh** [comment]
Sure, Why not. שני.

**Comment by shanielh** [comment]
What license file should I use? :)

**Comment by joliss** [comment]
MIT is the most popular choice (and a great license).

You can copy it from here, just put the year and your name: https://github.com/joliss/broccoli/blob/master/LICENSE :)

**Comment by shanielh** [comment]
Done, Thanks.
